# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters. 
# New version suggested by Github Copilot, with further suggestions from Ask.firstdraft.com
name: Ruby on Rails CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(rbenv init -)"
        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
        export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
        eval "$(rbenv init -)"
        rbenv install 3.2.1
        rbenv global 3.2.1
        ruby -v

    - name: Verify rbenv installation
      run: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(rbenv init -)"
        rbenv --version

    - name: Install dependencies
      run: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(rbenv init -)"
        gem install bundler
        bundle install

    - name: Run tests
      run: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(rbenv init -)"
        bundle exec rake
